routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/accesinterdit',function(){
  return view('accesinterdit');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('users/block/{id}', 'UserController@block')->name('users.block');
Route::get('users/block/{id}', 'UserController@block')->name('users.block');
Route::post('alertes/consulte/{id}', 'AlerteController@consulte')->name('alertes.consulte');
Route::get('alertes/consulte/{id}', 'AlerteController@consulte')->name('alertes.consulte');


Route::resource('users', 'UserController');
Route::resource('capteurs', 'CapteurController');
Route::resource('type_intervs', 'TypeIntervController');
Route::resource('interventions', 'InterventionController');
Route::resource('historiques', 'HistoriqueController');
Route::resource('factures', 'FactureController');
Route::resource('etablissements', 'EtablissementController');
Route::resource('alertes', 'AlerteController');

app/Etablissement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Etablissement extends Model
{
  protected $fillable = [
  'nom',
  'email',
  'telephone'
];
}

app/Http/Controllers/EtablissementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Etablissement;

class EtablissementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $etablissements = Etablissement::all();

      return view('etablissements.index', compact('etablissements'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('etablissements.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
      'nom'=>'required',
      'email'=>'required|email',
      'telephone'=>'required|integer'
    ]);

    $etablissement = new Etablissement([
      'nom' => $request->get('nom'),
      'email' => $request->get('email'),
      'telephone' => $request->get('telephone')
    ]);

    $etablissement->save();
    return redirect('/etablissements');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $etablissement = Etablissement::find($id);

      return view('etablissements.edit', compact('etablissement'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
        'nom'=>'required',
        'email'=> 'required',
        'telephone' => 'required|numeric'
    ]);

    $etablissement = Etablissement::find($id);
    $etablissement->nom = $request->get('nom');
    $etablissement->email = $request->get('email');
    $etablissement->telephone = $request->get('telephone');
    $etablissement->save();

    return redirect('/etablissements');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $etablissement = Etablissement::find($id);
      $etablissement->delete();
      return redirect('/etablissements');
    }
    public function __construct()
    {
    $this->middleware('auth');
    $this->middleware('etablissement');}
}

resources/views/etablissements/create.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 20px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Ajouter Établissement
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('etablissements.store') }}">
        <div class="col-4">
          <div class="form-group">
              @csrf
              <label for="email">Nom Établissement:</label>

              <input type="text" class="form-control" name="nom"/>
            </div>
          </div>
            <div class="col-4">
          <div class="form-group">
              <label for="password">E-Mail:</label>
              <input type="email" class="form-control" name="email"/>
          </div>
          <div class="form-group">
              <label for="telephone">Téléphone:</label>
              <input type="text" class="form-control" name="telephone"/>
          </div>
        </div>
          <button type="submit" class="btn btn-primary">Confirmer</button>
      </form>
  </div>
</div>
@endsection

resources/views/etablissements/edit.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 20px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Modifier Établissement
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('etablissements.update', $etablissement->id) }}">
        @method('PATCH')
        @csrf
        <div class="col-5">
        <div class="form-group">
          <label for="nom">Nom Etablissement :</label>
          <input type="text" class="form-control" name="nom" value="{{ $etablissement->nom }}" />
        </div>
        <div class="form-group">
          <label for="price">E-Mail :</label>
             <input type="text" class="form-control" name="email" value="{{ $etablissement->email }}" />
        </div>
        <div class="form-group">
          <label for="quantity">Telephone:</label>
          <input type="text" class="form-control" name="telephone" value="{{ $etablissement->telephone }}" />
        </div>
      </div>
          <button type="submit" class="btn btn-primary">Confirmer</button>
      </form>
  </div>
</div>
@endsection

resources/views/etablissements/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 20px;
  }
  .card-header {
   display: block;
}

</style>

<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif

<div class="card" style="width:77%; margin: auto;">
  <div class="card-header">
    <p style="font-size:20px">Établissements
    <span class="float-right" ><a href="etablissements/create" style="font-size:14px;" class="btn btn-outline-secondary btn-sm" >Ajouter Établissement +</a>
    </span></p>
  </div>
                  <div class="table-responsive" width="100%">
                    <div class="container" >
                    <table id="id" class="table card-table table-vcenter text-nowrap" style="margin: auto;
  width: 97%;
  padding: 10px;" width="97%">
                      <thead>
                        <tr>
                          <th class="w-1">ID.</th>
                          <th>Nom d'établissement</th>
                          <th>E-Mail</th>
                          <th>Telephone</th>
                          <th></th>
                          <th>
                        </th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($etablissements as $etablissement)
                        <tr>
                          <td><span class="text-muted">{{$etablissement->id}}</span></td>
                          <td>{{$etablissement->nom}}</td>
                          <td>
                            {{$etablissement->email}}
                          </td>

                          <td>
                            {{$etablissement->telephone}}
                          </td>

                          <td class="text-right">
                            <a class="icon" href="{{ route('etablissements.edit',$etablissement->id)}}" data-balloon="Modifier" data-balloon-pos="right">
                              <i class="fe fe-edit"></i>
                            </a>
                          </td>
                          <td>

                            <form action="{{ route('etablissements.destroy', $etablissement->id) }}" method="POST">
{{ method_field('DELETE') }}
{{ csrf_field() }}
        <button type='submit' style="	background: none;
  	           color: #9aa0ac;
              	border: none;
	               padding: 0;
	                font: inherit;
	                 cursor: pointer;
	                  outline: inherit;" ><i class="fe fe-trash-2" style="color: inherit;" ></i></button>
                              </form>

                          </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>



@endsection