routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/accesinterdit',function(){
  return view('accesinterdit');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('users/block/{id}', 'UserController@block')->name('users.block');
Route::get('users/block/{id}', 'UserController@block')->name('users.block');
Route::post('alertes/consulte/{id}', 'AlerteController@consulte')->name('alertes.consulte');
Route::get('alertes/consulte/{id}', 'AlerteController@consulte')->name('alertes.consulte');


Route::resource('users', 'UserController');
Route::resource('capteurs', 'CapteurController');
Route::resource('type_intervs', 'TypeIntervController');
Route::resource('interventions', 'InterventionController');
Route::resource('historiques', 'HistoriqueController');
Route::resource('factures', 'FactureController');
Route::resource('etablissements', 'EtablissementController');
Route::resource('alertes', 'AlerteController');

app/Capteur.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Capteur extends Model
{
  protected $fillable = [
  'code_capteur',
  'etat',
  'etab'
];
}

app/Http/Controllers/CapteurController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Capteur;

class CapteurController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $capteurs = Capteur::all();

      return view('capteurs.index', compact('capteurs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('capteurs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
      'code_capteur'=>'required|integer',
      'etab' => 'required'
    ]);

    $capteur = new Capteur([
      'code_capteur' => $request->get('code_capteur'),
      'etab' => $request->get('etab')
    ]);

    $capteur->save();
    return redirect('/capteurs');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $capteur = Capteur::find($id);
      $capteur->delete();
      return redirect('/capteurs');
    }
    public function __construct()
    {
    $this->middleware('auth');
    $this->middleware('capteur');}
}

resources/views/capteurs/create.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 20px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Ajouter Capteur
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('capteurs.store') }}">
        <div class="col-6">
          <div class="form-group">
              @csrf
              <label for="name">Code Capteur:</label>
              <input type="text" class="form-control" name="code_capteur"/>
              @if (Auth::user()->usertype=="super")
              <label for="etab">Établissement:</label>
              <select class="form-control" name="etab">
                  <?php
                  $pdo = new PDO('mysql:host=localhost;dbname=gestionpreventionincendie;charset=utf8', 'root', '');
                  $sql = "SELECT * FROM etablissements";
                  $stmt = $pdo->prepare($sql);
                  $stmt->execute();
                  $etabs = $stmt->fetchAll();
                   foreach($etabs as $etab): ?>
                  <option value="<?= $etab['nom']; ?>" name="etab">
                  <?= $etab['nom']; ?></option>
                  <?php endforeach; ?>
              </select>
              @else
              <input id="etab" name="etab" type="hidden" value="{{Auth::user()->etab}}">
              @endif
          </div>
          <button type="submit" class="btn btn-primary">Confirmer</button>
        </div>
      </form>
  </div>
</div>
@endsection

resources/views/capteurs/index.blade.php
@extends('layouts.app')
<?php use App\Capteur;?>
@section('content')
<style>
  .uper {
    margin-top: 20px;
  }
  .card-header {
   display: block;

}
.form-button {
	background: none;
	color: inherit;
	border: none;
	padding: 0;
	font: inherit;
	cursor: pointer;
	outline: inherit;
}

</style>

<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif

<div class="card" style="width:50%; margin: auto;">
  <div class="card-header">
    <p style="font-size:20px">Capteurs
    <span class="float-right" ><a href="capteurs/create" style="font-size:14px;" class="btn btn-outline-secondary btn-sm" >Ajouter Capteur +</a>
    </span></p>
  </div>
                  <div class="table-responsive">
                    <div class="container">
                    <table id="id" class="table card-table table-vcenter text-nowrap" style="margin: auto;
  width: 70%;
  padding: 10px;" >
                      <thead>
                        <tr>
                        @if(Auth::user()->usertype == "super")  <th class="w-1">ID.</th> @endif
                          <th>Code Capteur</th>
                          <th>État</th>
                        @if (Auth::user()->usertype == "super") <th> Établissement</th> @endif
                          <th>Groupe</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($capteurs as $capteur)
                        <?php
                        $c = Capteur::find($capteur['parent']);
                        if($c['type']=="capteur"){
                          $etab = $c['etab'];
                        }
                        else {
                          $etab = $capteur['etab'];
                        }

                          ?>
                        @if((Auth::user()->etab==$capteur->etab || Auth::user()->usertype=="super") && $capteur['type']=="capteur")
                        <tr>
                        @if(Auth::user()->usertype == "super")   <td><span class="text-muted">{{$capteur->id}}</span></td> @endif
                          <td>{{$capteur->code_capteur}}</td>
                          <td>
                            {{$capteur->etat}}
                          </td>
                    @if (Auth::user()->usertype == "super")  <td> {{$etab}}</td>@endif
                    <td>{{$c['code_capteur']}}</td>

                          <td>
                            <form action="{{ route('capteurs.destroy', $capteur->id) }}" method="POST">
{{ method_field('DELETE') }}
{{ csrf_field() }}
<button type='submit' class="btn btn-danger" style="	background: none;
	color: #9aa0ac;
	border: none;
	padding: 0;
	font: inherit;
	cursor: pointer;
	outline: inherit;" ><i class="fe fe-trash-2" style="color: inherit;" ></i></button>
</form>
                          </td>
                        </tr>
                        @endif
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
@endsection