routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/accesinterdit',function(){
  return view('accesinterdit');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('users/block/{id}', 'UserController@block')->name('users.block');
Route::get('users/block/{id}', 'UserController@block')->name('users.block');
Route::post('alertes/consulte/{id}', 'AlerteController@consulte')->name('alertes.consulte');
Route::get('alertes/consulte/{id}', 'AlerteController@consulte')->name('alertes.consulte');


Route::resource('users', 'UserController');
Route::resource('capteurs', 'CapteurController');
Route::resource('type_intervs', 'TypeIntervController');
Route::resource('interventions', 'InterventionController');
Route::resource('historiques', 'HistoriqueController');
Route::resource('factures', 'FactureController');
Route::resource('etablissements', 'EtablissementController');
Route::resource('alertes', 'AlerteController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password', 'telephone', 'usertype','bloque', 'etab'
          ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $users = User::all();

      return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
              'email'=>'required|unique:users',
              'password'=> 'required',
              'telephone' => 'required|numeric|unique:users',
              'usertype' =>'required',
              'etab' => 'required'
            ]);
            $user = new User([
              'email' => $request->get('email'),
              'password'=> Hash::make($request['password']),
              'telephone'=> $request->get('telephone'),
              'usertype'=> $request->get('usertype'),
              'etab' => $request->get('etab')
            ]);
            $user->save();
            return redirect('/users');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $user = User::find($id);

      return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
        'email'=>'required',
        'password'=> 'required',
        'telephone' => 'required|numeric',
        'usertype' =>'required'
    ]);

    $user = User::find($id);
    $user->email = $request->get('email');
    $user->password =  Hash::make($request['password']);
    $user->telephone = $request->get('telephone');
    $user->usertype = $request->get('usertype');
    $user->save();

    return redirect('/users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
      $user = User::find($id);
   $user->delete();

   return redirect('/users')->with('success', 'Stock has been deleted Successfully');
    }

    public function block($id){
      $user = User::find($id);
      if ($user->bloque == 0){
      $user->bloque = 1 ;
      $user->save();
      return redirect('/users');}
      else{
        $user->bloque = 0;
        $user->save();
        return redirect('/users');
      }


    }

    public function __construct()
{
    $this->middleware('auth');
    $this->middleware('usertype');
}
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 20px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Ajouter Utilisateur
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('users.store') }}">
        <div class="col-4">
          <div class="form-group">
              @csrf
              <label for="email">Pseudo Utilisateur:</label>

              <input type="text" class="form-control" name="email"/>
            </div>


          <div class="form-group">
              <label for="password">Mot de passe:</label>
              <input type="password" class="form-control" name="password" />
          </div>
          <div class="form-group">
              <label for="telephone">Telephone:</label>
              <input type="text" class="form-control" name="telephone" />
          </div>
          @if(Auth::user()->usertype=="super")<div class="form-group">
            <label for="etab">Établissement:</label>
            <select class="form-control" name="etab">
                <?php
                $pdo = new PDO('mysql:host=localhost;dbname=gestionpreventionincendie;charset=utf8', 'root', '');
                $sql = "SELECT * FROM etablissements";
                $stmt = $pdo->prepare($sql);
                $stmt->execute();
                $etabs = $stmt->fetchAll();
                 foreach($etabs as $etab): ?>
                <option value="<?= $etab['nom']; ?>" name="etab">
                <?= $etab['nom']; ?></option>
                <?php endforeach; ?>
            </select>
          </div>
          @else
            <input id="etab" name="etab" type="hidden" value="{{Auth::user()->etab}}">
          @endif
        </div>
        <div class="col-10">
          <div class="form-group">
            <label for="usertype">Type Utilisateur:</label>
            <input id="normal" type="radio" name="usertype" value="normal" checked> Normal     </input>
           <input id="admin" type="radio" name="usertype" value="admin"> Administrateur      </input>
           @if (Auth::user()->usertype=="super")<input id="super" type="radio" name="usertype" value="super"> Super Utilisateur    </input>@endif
            @if ($errors->has('usertype'))
            <span class="help-block">
            <strong>{{ $errors->first('usertype') }}</strong>
            </span>
            @endif
           </div>
</div>
          <button type="submit" class="btn btn-primary">Confirmer</button>
      </form>
  </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 20px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Modifier Utilisateur
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('users.update', $user->id) }}">
        @method('PATCH')
        @csrf
        <div class="col-5">
        <div class="form-group">
          <label for="username">Pseudo Utilisateur:</label>
          <input type="text" class="form-control" name="email" value={{ $user->email }} />
        </div>
        <div class="form-group">
          <label for="price">Mot de Passe:</label>
          <input type="password" class="form-control" name="password" placeholder="Insérer un nouveau mot de passe..." />
        </div>
        <div class="form-group">
          <label for="quantity">Telephone:</label>
          <input type="text" class="form-control" name="telephone" value={{ $user->telephone }} />
        </div>
      </div>
      <div class="col-10">
        <div class="form-group">
          <label for="usertype">Type Utilisateur:</label><br/>
           <input id="normal" type="radio" name="usertype" value="normal"<?php if ($user->usertype=="normal"): ?> checked<?php endif;?> > Normal    </input>
          <input id="admin" type="radio" name="usertype" value="admin" <?php if ($user->usertype=="admin"): ?> checked <?php endif;?>> Administrateur      </input>
          @if (Auth::user()->usertype=="super")<input id="super" type="radio" name="usertype" value="super"> Super Utilisateur    </input>@endif
           @if ($errors->has('usertype'))
           <span class="help-block">
           <strong>{{ $errors->first('usertype') }}</strong>
           </span>
           @endif
           </div>

          <br/>
        </div>
          <button type="submit" class="btn btn-primary">Confirmer</button>
      </form>
  </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 20px;
  }
  .card-header {
   display: block;
}

</style>

<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif

<div class="card" style="width:77%; margin: auto;">
  <div class="card-header">
    <p style="font-size:20px">Utilisateurs
    <span class="float-right" ><a href="users/create" style="font-size:14px;" class="btn btn-outline-secondary btn-sm" >Ajouter Utilisateur +</a>
    </span></p>
  </div>
                  <div class="table-responsive" width="100%">
                    <div class="container" >
                    <table id="id" class="table card-table table-vcenter text-nowrap" style="margin: auto;
  width: 97%;
  padding: 10px;" width="97%">
                      <thead>
                        <tr>
                          @if (Auth::user()->usertype=="super")<th class="w-1">ID.</th>@endif
                          <th>Pseudo Utilisateur</th>
                          <th>Telephone</th>
                          <th>Type Utilisateur</th>
                          <th>État</th>
                          @if (Auth::user()->usertype=="super")<th>Établissement</th>@endif
                          <th></th>
                          <th>
                        </th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($users as $user)
                        @if ($user->etab==Auth::user()->etab || Auth::user()->etab==null )
                        <tr>
                          @if (Auth::user()->usertype=="super")<td><span class="text-muted">{{$user->id}}</span></td>@endif
                          <td>{{$user->email}}</td>
                          <td>
                            {{$user->telephone}}
                          </td>
                          <?php if ($user->usertype=="normal"): ?>
                          <td>
                            Utilisateur Normal
                          </td>
                        <?php elseif ($user->usertype=="admin"): ?>
                          <td>
                            Administrateur
                          </td>
                        <?php else: ?>
                          <td>Super Utilisateur</td>
                        <?php endif; ?>
                          <?php if ($user->bloque==1): ?>
                          <td><span class="status-icon bg-danger"></span>Bloqué</td>
                        <?php else: ?>
                          <td><span class="status-icon bg-success"></span>Actif</td>
                          <?php endif; ?>
                          @if(Auth::user()->usertype=="super")<td>
                            {{$user->etab}}
                          </td>@endif
                          <td class="text-right">
                            <a class="icon" href="{{ route('users.edit',$user->id)}}" data-balloon="Modifier" data-balloon-pos="right">
                              <i class="fe fe-edit"></i>
                            </a>
                          </td>
                          <td>

                                <a class="icon" href="{{ route('users.block',$user->id)}}" <?php if ($user->bloque==1): ?> data-balloon="Débloquer" <?php else: ?> data-balloon="Bloquer" <?php endif;?> data-balloon-pos="right">
                                  <i <?php if ($user->bloque==1): ?> class="fe fe-unlock" <?php else: ?> class="fe fe-lock"  <?php endif;?> ></i>
                                </a>

                          </td>

                        </tr>
                        @endif
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>



@endsection