routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/accesinterdit',function(){
  return view('accesinterdit');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('users/block/{id}', 'UserController@block')->name('users.block');
Route::get('users/block/{id}', 'UserController@block')->name('users.block');
Route::post('alertes/consulte/{id}', 'AlerteController@consulte')->name('alertes.consulte');
Route::get('alertes/consulte/{id}', 'AlerteController@consulte')->name('alertes.consulte');


Route::resource('users', 'UserController');
Route::resource('capteurs', 'CapteurController');
Route::resource('type_intervs', 'TypeIntervController');
Route::resource('interventions', 'InterventionController');
Route::resource('historiques', 'HistoriqueController');
Route::resource('factures', 'FactureController');
Route::resource('etablissements', 'EtablissementController');
Route::resource('alertes', 'AlerteController');

app/TypeInterv.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TypeInterv extends Model
{
  protected $fillable = [
  'type'
];
}

app/Http/Controllers/TypeIntervController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\TypeInterv;

class TypeIntervController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $type_intervs = TypeInterv::all();

      return view('type_intervs.index', compact('type_intervs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('type_intervs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
      'type'=>'required|string'
    ]);

    $type_interv = new TypeInterv([
      'type' => $request->get('type')
    ]);

    $type_interv->save();
    return redirect('/type_intervs');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $type_interv = TypeInterv::find($id);
      $type_interv->delete();
      return redirect('/type_intervs');
    }
    public function __construct()
    {
    $this->middleware('auth');
    $this->middleware('type_interv');}
}

resources/views/type_intervs/create.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Ajouter Type Intervention
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('type_intervs.store') }}">
        <div class="col-6">
          <div class="form-group">
              @csrf
              <label for="name">Libellé:</label>
              <input type="text" class="form-control" name="type"/>
              @if(Auth::user()->usertype=="super")<div class="form-group">
                <label for="etab">Établissement:</label>
                <select class="form-control" name="etab">
                    <?php
                    $pdo = new PDO('mysql:host=localhost;dbname=gestionpreventionincendie;charset=utf8', 'root', '');
                    $sql = "SELECT * FROM etablissements";
                    $stmt = $pdo->prepare($sql);
                    $stmt->execute();
                    $etabs = $stmt->fetchAll();
                     foreach($etabs as $etab): ?>
                    <option value="<?= $etab['nom']; ?>" name="etab">
                    <?= $etab['nom']; ?></option>
                    <?php endforeach; ?>
                </select>
              </div>@endif
          </div>
          <button type="submit" class="btn btn-primary">Confirmer</button>
        </div>
      </form>
  </div>
</div>
@endsection

resources/views/type_intervs/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
  .card-header {
   display: block;

}
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif

<div class="card" style="width:50%; margin: auto;">
  <div class="card-header">
    <p style="font-size:20px">Types Intervention
    <span class="float-right" ><a href="type_intervs/create" style="font-size:14px;" class="btn btn-outline-secondary btn-sm" >Ajouter Type Intervention +</a>
    </span></p>
  </div>
                  <div class="table-responsive">
                    <div class="container">
                    <table id="id" class="table card-table table-vcenter text-nowrap" style="margin: auto;
  width: 70%;
  padding: 10px;" >
                      <thead>
                        <tr>
                          <th class="w-1">ID.</th>
                          <th>Libellé</th>
                          @if (Auth::user()->usertype=="super")<th>Établissement</th>@endif
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($type_intervs as $type_interv)
                        @if ($type_interv->etab==Auth::user()->etab || Auth::user()->usertype=="super" )
                        <tr>
                          <td><span class="text-muted">{{$type_interv->id}}</span></td>
                          <td>{{$type_interv->type}}</td>
                          @if (Auth::user()->usertype=="super")<td>{{$type_interv->etab}}</td>@endif
                          <td>
                            <form action="{{ route('type_intervs.destroy', $type_interv->id) }}" method="POST">
{{ method_field('DELETE') }}
{{ csrf_field() }}
        <button type='submit' class="btn btn-danger" style="	background: none;
  	           color: #9aa0ac;
              	border: none;
	               padding: 0;
	                font: inherit;
	                 cursor: pointer;
	                  outline: inherit;" ><i class="fe fe-trash-2" style="color: inherit;" ></i></button>
                              </form>
                        </tr>
                        @endif
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
@endsection